#ifndef  _CONFIG_H_
#define  _CONFIG_H_

#define TRANSITION_TIME 2

#define BIRD_CATEGORY_BITMASK 0x01
#define PIPE_CATEGORY_BITMASK 0x02
#define EDGE_CATEGORY_BITMASK 0x04
#define POINT_CATEGORY_BITMASK 0x08

#define BIRD_VELOCITY 100
#define PIPE_VELOCITY 0.01

#define PIPE_GAP_DISTANCE 5

#define SCORE_FONT_SIZE 0.1

#endif // _CONFIG_H_

